name: ci

on: push

jobs:
    build:
      runs-on: ubuntu-16.04
      strategy:
        matrix:
          node: [ '10', '12' ]
      name: Node ${{ matrix.node }} sample
      steps:
        - uses: actions/checkout@v2
        - name: Setup rust
          uses: actions-rs/toolchain@v1.0.6      
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
        - run: npm run ci:run