name: ci

on: push

jobs:
    build:
      runs-on: ubuntu-16.04
      strategy:
        matrix:
          node: [ '10', '12' ]
      name: Node ${{ matrix.node }} sample
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true
            components: rustfmt, clippy
        - uses: actions-rs/cargo@v1
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
        - run: npm run ci:run